# Copyright 2024 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and .Values.clusterRoleBinding.install }}
{{- $fullname := include "qubership-prometheus-adapter-operator.fullname" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
  labels:
    name: {{ $fullname }}
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/instance: {{ cat $fullname "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    {{- include "qubership-prometheus-adapter-operator.commonlLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "qubership-prometheus-adapter-operator.fullname" . }}
{{- end }}
